"""empty message

Revision ID: 09c64b7db56e
Revises: b2b5904b2c3f
Create Date: 2020-09-19 19:29:09.647791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09c64b7db56e'
down_revision = 'b2b5904b2c3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job__post', sa.Column('job_city', sa.String(length=120), nullable=False))
    op.add_column('job__post', sa.Column('job_payment', sa.String(length=10), nullable=False))
    op.add_column('job__post', sa.Column('job_state', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job__post', 'job_state')
    op.drop_column('job__post', 'job_payment')
    op.drop_column('job__post', 'job_city')
    # ### end Alembic commands ###
